[versions]
junit-jupiter = "5.10.3"
kotlinx-html = "0.12.0"
klite = "1.7.0"
hikari = "6.3.0"
h2 = "2.3.232"
snakeyaml = "2.4"
[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinx-html" }
klite-server = { module = "com.github.codeborne.klite:klite-server", version.ref = "klite" }
klite-jdbc = { module = "com.github.codeborne.klite:klite-jdbc", version.ref = "klite" }
klite-json = { module = "com.github.codeborne.klite:klite-json", version.ref = "klite" }
klite-liquibase = { module = "com.github.codeborne.klite:klite-liquibase", version.ref = "klite" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
[bundles]
[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.0" }