import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app ABOUT",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
    <h1> About with in layout</h1>
      {children}
  </div>
  );
}
