services:
  postgres:
    image: postgres:16.10-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    command: postgres -c max_connections=1000
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - dataflow-network

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=oblik@oblik.com
      - PGADMIN_DEFAULT_PASSWORD=oblik
    depends_on:
      - postgres
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo '*:5432:restaurant:restaurant:restaurant' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - ${PGADMIN_PORT}:80
    profiles:
      - local


networks:
  dataflow-network:

volumes:
  postgres-data:
